# logging options
save_dir: </path/to/logging/dir>
project: <project_name>
name: debug

# task definition
data_config: data_config.yaml
task: <binary/multiclass/multilabel>
target: <target>
num_classes: <int>
cohorts: ["<cohort_name1>", "<cohort_name2>"]
ext_cohorts: ["<external_cohort_name>"]
clini_info: {}
seed: null
label_dict:
  <class_0>: 0
  <class_1>: 1

# model options
model: <Transformer/TransMIL/AttentionMIL/...>
model_config: null
norm: <normalizatio_used>
feats: <feature_extractor_used>
input_dim: <feature_dim>
num_tiles: -1
pad_tiles: false

# training options
folds: 5
num_epochs: 1
criterion: <BCEWithLogitsLoss/CrossEntropyLoss/...>
optimizer: <AdamW/Adam/...>
lr_scheduler: null
lr_scheduler_config: null
lr: 2.0e-05
wd: 2.0e-05
bs: 1
stop_criterion: loss
val_check_interval: 500
num_samples: null
